name: api@production

on:
  workflow_dispatch:
  push:
    tags:
      - "api@*"

env:
  pnpm-version: 9
  node-version: 20

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CLOUDFLARE_SUBMODULE }}

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpm-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - run: pnpm install -P

      - run: pnpm build
        working-directory: apps/cloudflare

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: api:production
      url: https://cloudflare.frontendista.cz

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.CLOUDFLARE_SUBMODULE }}

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpm-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - name: Deploy
        run: pnpm deploy:prod
        working-directory: apps/cloudflare
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
