name: 👀 CMS CI

on:
  push:
    branches: [main]
    paths:
      - "apps/cms/**"
      - ".github/workflows/cms-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/cms/**"
      - ".github/workflows/cms-ci.yml"

defaults:
  run:
    working-directory: apps/cms

jobs:
  build:
    name: 👷🏽‍♂️ Build
    # TODO: Do a more sofisticated check, this has undesired edge-cases.
    if: ${{ !startsWith(github.event.head_commit.message, 'docs') && !startsWith(github.event.head_commit.message, 'style') }}
    runs-on: ubuntu-latest

    steps:
      - name: 👉 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 👟 Build
        run: pnpm build

  lint:
    name: 🔎 ESLint
    runs-on: ubuntu-latest

    steps:
      - name: 👉 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: 📦 Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 👟 Run ESLint
        run: pnpm lint
