name: 🚚 FRONTEND CD

# TODO: Change to manual dispatch
on:
  release:
    types: [created]

jobs:
  deploy:
    name: ⬆️ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: TODO
        run: echo TODO
