name: 👀 FRONTEND CI

on:
  push:
    branches: [main]
    paths:
      - "apps/frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/frontend/**"
      - ".github/workflows/frontend-ci.yml"

defaults:
  run:
    working-directory: apps/frontend

env:
  SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
  SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
  SANITY_DATASET_ID: ${{ secrets.SANITY_DATASET_ID }}

jobs:
  build:
    name: 👷🏽‍♂️ Build
    # TODO: Do a more sofisticated check, this has undesired edge-cases.
    if: ${{ !startsWith(github.event.head_commit.message, 'docs') && !startsWith(github.event.head_commit.message, 'style') }}
    runs-on: ubuntu-latest

    steps:
      - name: 👉 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 👟 Build
        run: pnpm build

  format:
    name: 🔎 Svelte Check
    runs-on: ubuntu-latest

    steps:
      - name: 👉 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: 📦 Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 👟 Run check
        run: pnpm check

  lint:
    name: 🔎 ESLint
    runs-on: ubuntu-latest

    steps:
      - name: 👉 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: 📦 Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 👟 Run ESLint
        run: pnpm lint

  bundlewatch:
    name: 🔎 BundleWatch
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: 👉 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      # HACK: Preactjs size action uses simple algorithm for choosing correct package manager.
      # As our pnpm-lock.yaml file lives in root of monorepo it doesn't choose correct package manager.
      - name: HACK
        run: touch pnpm-lock.yaml

      - name: 👟 Run Bundlewatch
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: "./.vercel_build_output/static/**/*.{js,css,html}"
          strip-hash: "\\b-[a-z0-9]{1,}\\b"
          compression: "brotli"
          cwd: apps/frontend

  unit:
    name: 🔎 Unit Testing
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: 👉 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: 📦 Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 👟 Run Vitest
        run: pnpm test:unit

  e2e:
    name: 🔎 E2E Testing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: [build]

    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: 👉 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: 📦 Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: 📀 Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
            ~/Library/Caches/ms-playwright
            C:\Users\runneradmin\AppData\Local\ms-playwright
          # TODO: Automatically get playwright version from manifest
          key: cache-playwright-1.22.2-${{ matrix.os }}

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔧 Install playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm playwright install --with-deps chromium firefox webkit 

      - name: 👟 Run your tests
        run: pnpm test:e2e:ci
