name: web@ci

on:
  workflow_dispatch:
  pull_request: 
    branches: 
      - main
    paths: 
      - "apps/web/**"
  push: 
    branches: 
      - main
    paths: 
      - "apps/web/**"

env:
  pnpm-version: 8
  node-version: 18

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm lint
        working-directory: apps/web

  check:
    name: Type-check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm type-check
        working-directory: apps/web

  build:
    name: Build
    needs: [lint, check]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"

      - run: pnpm install -P

      - run: pnpm build
        working-directory: apps/web

  test:
    name: E2E
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.pnpm-version }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: "pnpm"

    - run: pnpm install

    - run: pnpm exec playwright install --with-deps
      working-directory: apps/web

    - run: pnpm test
      working-directory: apps/web

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: apps/web/playwright-report/
        retention-days: 7
